### ISSUE TITLE
企業アカウント登録が住所未入力でも成功してしまう

### ISSUE THREAD

**Issue by Hanachanm** [naoki-k/MPay#11]
## 問題
企業アカウントを登録する際、本来必須のはずの住所を入力せず登録ボタンを押すと
Userの登録に成功してしまう。
CorporateInformationは未登録のままである。
また、バリデーションエラーも表示されない。（リダイレクトしてるから…？）

### 入力した情報
<img width="585" alt="スクリーンショット 2019-08-22 16 48 25" src="https://user-images.githubusercontent.com/33307379/63496591-2a7b3b80-c4fd-11e9-8cd2-b6e6f07d42ac.png">

### 表示されたflashメッセージ
<img width="637" alt="スクリーンショット 2019-08-22 16 53 47" src="https://user-images.githubusercontent.com/33307379/63496759-6d3d1380-c4fd-11e9-97e5-ef7bbfb0c82a.png">

### 疑問
flashの`info`と`danger`ってどう使い分けてるんだろ🤔

**Comment by naoki-k** [comment]
別のオブジェクトを保存するから、一方(Userモデル)のみの保存を許可するように設計してた。
画面で見ると、ユーザーは別々の登録に感じないから同時登録を必須に修正する！

バリデーションエラーが表示されないのは、オブジェクトが違うから。
そこらへんも修正します...

> flashのinfoとdangerってどう使い分けてるんだろ🤔

次のフェーズに進んだけど、注意があるよ、ってのがinfoのイメージ

**Comment by Hanachanm** [comment]
なるほど！
まあ同時保存できた方がよろしい感じする、ファイト！お願いします💪
