### ISSUE TITLE
利用する色を変数で定義しておく

### ISSUE THREAD

**Issue by Hanachanm** [naoki-k/MPay#13]
## 問題
各ファイルで変数定義するとうまくいくけど、
別ファイルで定義すると変数がないって言われる。

## その他
利用する色決めるの面倒&激ムズなので、mwedの配色を利用します。😂
それによってheaderの色等も変わる予定。
ロゴも寄せてもらえるとうれしい。

**Comment by naoki-k** [comment]
頑張れ頑張れできるできる絶対できる頑張れもっとやれるって！

**Comment by naoki-k** [comment]
> ロゴも寄せてもらえるとうれしい

らじゃ🙆‍♂️

**Comment by naoki-k** [comment]
> 各ファイルで変数定義するとうまくいくけど、
別ファイルで定義すると変数がないって言われる。

各ファイルでimportすればいけるよ

手動でリソースを`application.css`にimportするなら、先に読み込ませればいいみたい
