### ISSUE TITLE
ユーザー一覧画面のレイアウト作成

### ISSUE THREAD

**Issue by naoki-k** [naoki-k/MPay#5]
内容
---
`/users` のレイアウト作成

管理者ユーザーのみがアクセスできる(今後そのようにする)。
この画面では、企業ユーザーおよび管理者ユーザーのアカウント有効化・削除を行うことができる

アカウント有効化のフローは以下の通り
```
個人ユーザー: 登録ボタン → メールのリンクを踏んで本登録
企業ユーザー: 登録ボタン → システムに申請される → 管理者が有効化する
管理者ユーザー: 登録ボタン → システムに申請される → 管理者が有効化する
```

タスク
---
- `/users` のレイアウト作成
- 企業ユーザー一覧/管理者ユーザー一覧 を切り替えられるようにする

現状レイアウト
---
<img src="https://user-images.githubusercontent.com/33798910/63492302-2d256300-c4f4-11e9-8e4f-c597325e1e77.png">

**Comment by Hanachanm** [comment]
> 企業ユーザー一覧/管理者ユーザー一覧 を切り替えられるようにする

これ用のボタン的な何かしらはうちが実装したらいい感じでしょうか？
@naoki-k

**Comment by naoki-k** [comment]
@Hanachanm 
できれば...？

返事遅れましてごめんなさい

**Comment by Hanachanm** [comment]
@naoki-k 実装しております🙆‍♀️
